/* eslint-disable */
// TEST-ONLY ephemeral key — regenerated by /tmp/test-sign.mjs
// Do NOT commit this state. Restore from backup before git operations.
export const TRUSTED_PUBKEY_B64 = '2uS34a7epEkWTbe89kQprguQqnuiIm8Dq+6MeJ2H5n4=';
export const TRUSTED_PUBKEY_FINGERPRINT = 'ed25519:dae4b7e1aedea449';
